name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: run tests
        run: go test -cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: run security checks
        run: gosec ./...

  Style:
    name: Style
    runs-on: ubuntu-latest # Needed

    steps:
      - name: Check out code
        uses: actions/checkout@v4 # Needed

      - name: Set up Go
        uses: actions/setup-go@v5 # Needed
        with:
          go-version: "1.23.0" # Specify Go version

      - name: run go fmt check
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: run staticcheck
        run: staticcheck ./...
